#!/usr/bin/env bash
###############################################################################
#
# Bash Remediation Script generated from evaluation of CIS Ubuntu Linux 22.04 LTS Benchmark for Level 2 - Server
#
# Profile ID: xccdf_org.ssgproject.content_profile_cis_level2_server
# XCCDF Version:  unknown
#
# Evaluation Start Time:  2026-01-09T18:18:15+00:00
# Evaluation End Time:  2026-01-09T18:18:16+00:00
#
# This file was generated by OpenSCAP 1.4.2 using:
# $ oscap xccdf generate fix --result-id xccdf_org.open-scap_testresult_xccdf_org.ssgproject.content_profile_cis_level2_server --fix-type bash xccdf-results.xml
#
# This Bash Remediation Script is generated from the results of a profile evaluation.
# It attempts to remediate all issues from the selected rules that failed the test.
#
# How to apply this Bash Remediation Script:
# $ sudo ./remediation-script.sh
#
###############################################################################

###############################################################################
# BEGIN fix (1 / 1) for 'xccdf_org.ssgproject.content_rule_permissions_local_var_log'
###############################################################################
(>&2 echo "Remediating rule 1/1: 'xccdf_org.ssgproject.content_rule_permissions_local_var_log'"); (




find -P /var/log/  -perm /u+xs,g+xws,o+xwrt ! -name 'history.log*' ! -name 'eipp.log.xz*' ! -name '[bw]tmp' ! -name '[bw]tmp.*' ! -name '[bw]tmp-*' ! -name 'lastlog' ! -name 'lastlog.*' -type f -regextype posix-extended -regex '.*' -exec chmod u-xs,g-xws,o-xwrt {} \;

) # END fix for 'xccdf_org.ssgproject.content_rule_permissions_local_var_log'

