#!/bin/bash

set -euo pipefail
. /.functions

REPOSITORY_ID="arkcase.thirdparty"
REPOSITORY="https://nexus.armedia.com/repository/arkcase.thirdparty"

GROUP_ID="org.apache.tika"

BASE_VERSION="3.3.1"
VERSION="${BASE_VERSION}-arm01"

JARS=(
	tika-app
	tika-emitter-fs
	tika-emitter-jdbc
	tika-emitter-s3
	tika-emitter-solr
	tika-fetcher-s3
	tika-server-standard
)

list_jars()
{
	for JAR in "${@}" ; do
		find . -type f -ipath '*/target/*' -name "${JAR}-${BASE_VERSION}.jar"
	done | sort -u
}

if ROOT="$(git rev-parse --show-toplevel 2>&1)" ; then
	cd "${ROOT}" || fail "Failed to CD into the Git root [${ROOT}] (rc=${?})"
else
	warn "Not in a git repository - so YMMV (rc=${?}: ${ROOT})"
fi

while read FILE ; do
	SRC_FILE="$(readlink -f "${FILE}")"

	NAME="$(basename "${FILE}")"
	PACKAGING="${NAME##*.}"
	NAME="${NAME%.*}"

	ARTIFACT_ID="${NAME//-${BASE_VERSION}/}"

	CMD=(
		mvn deploy:deploy-file
			-DrepositoryId="${REPOSITORY_ID}"
			-Durl="${REPOSITORY}"
			-DgroupId="${GROUP_ID}"
			-DartifactId="${ARTIFACT_ID}"
			-Dversion="${VERSION}"
			-Dpackaging="${PACKAGING}"
			-Dfile="${SRC_FILE}"
	)

	doing "Deploying [${SRC_FILE}]..."
	OUT="$( echo "${CMD[@]}" 2>&1 )" || fail "Failed to deploy [${SRC_FILE}] (rc=${?}):\n\tCommand: [ ${CMD[@]@Q} ]\n\n${OUT}"
	ok "Deployed!"
done < <(list_jars "${JARS[@]}")
