#!/bin/bash

set -euo pipefail
. /.functions

#
# Init all the SSL-related stuff
#
init_ssl

render_configuration()
{
	local CONFIG="${1}"
	local FINAL_CONFIG="${2}"

	is_file_readable "${CONFIG}" || return 1

	eyes "Trying the Tika configuration from [${CONFIG}]"
	RC=0
	OUT="$(xmllint "${CONFIG}" 2>&1)" || RC=${?}
	if [ ${RC} -ne 0 ] ; then
		err "The source configuration file at [${CONFIG}] was not valid XML (rc=${RC}): ${OUT}"
		return 1
	fi

	ok "The Tika configuration at [${CONFIG}] seems to be valid - will attempt to patch it!"
	if xmlenvsubst < "${CONFIG}" &> "${FINAL_CONFIG}" ; then
		ok "Patched the configuration from [${CONFIG}] with the required changes"

		# Verify the final result!
		OUT="$(xmllint "${FINAL_CONFIG}" 2>&1)" && return 0
		err "The final configuration file rendered from [${CONFIG}] was not valid XML (rc=${?}): ${OUT}"
	else
		err "Failed to process the configuration file from [${CONFIG}] (rc=${?}): $(<"${FINAL_CONFIG}")"
	fi

	return 1
}

require_dir_readable "${CONF_DIR}"
require_dir_readwrite "${LOGS_DIR}"
require_dir_readwrite "${TEMP_DIR}"

set_or_default JAVA_TOOL_OPTIONS ""

# Require SSL for Zookeeper
JAVA_TOOL_OPTIONS+="${JAVA_TOOL_OPTIONS:+ }-XX:MinRAMPercentage=50.0 -XX:MaxRAMPercentage=80.0 -Djava.util.logging.manager=org.apache.logging.log4j.jul.LogManager"

export TEMP="${TEMP_DIR}"
export TMP="${TEMP_DIR}"

set_or_default TIKA_CONFIG "${CONF_DIR}/tika-config.xml"
CONFIG_CANDIDATES=( "${TIKA_CONFIG}" "${CONF_DIR}/server.xml" )

set_or_default SSL_DIR
set_or_default POD_NAME "$(hostname -f)"
set_as_boolean DEBUG_LOG "false"

TIKA_CONF=()
FINAL_CONFIG="${CONF_DIR}/runtime-config-$(date -u "+%Y%m%d-%H%M%SZ").xml"
export LOG_LEVEL="info"
as_boolean "${DEBUG_LOG}" && LOG_LEVEL="debug"

for CONFIG in "${CONFIG_CANDIDATES[@]}" ; do
	render_configuration "${CONFIG}" "${FINAL_CONFIG}" || continue
	TIKA_CONF=( --config "${FINAL_CONFIG}" )
	break
done

# Build classpath using wildcards
set_or_default LIB_DIR "${BASE_DIR}/lib"
set_or_default EXTRA_CLASSPATH "${LIB_DIR}/*"
EXTRA_CLASSPATH="$(sanitize_pathspec "${EXTRA_CLASSPATH}")"
CP="${LIB_DIR}/*${EXTRA_CLASSPATH:+:}${EXTRA_CLASSPATH}"

# Build modulepath using wildcards
set_or_default MOD_DIR "${BASE_DIR}/mod"
set_or_default EXTRA_MOD_DIR
EXTRA_MOD_DIR="$(sanitize_pathspec "${EXTRA_MOD_DIR}")"
MP="${MOD_DIR}/*${EXTRA_MOD_DIR:+:}${EXTRA_MOD_DIR}"

set_or_default PORT "8443"
set_or_default EXTRA_ARGS

say "Starting Tika Server"
say "\tClasspath: ${CP}"
say "\tModule Path: ${MP}"
[ ${#TIKA_CONF[@]} -gt 0 ] && say "\tConfig: ${TIKA_CONF[@]}"
[ -n "${EXTRA_ARGS}" ] && say "\tArgs: [${EXTRA_ARGS}]"
say "\tListening on: *:${PORT}"

to_array EXTRA_ARGS || fail "The extra arguments string [${EXTRA_ARGS}] could not be converted into a BASH array"

set_or_default TIKA_SERVER_CLASS "org.apache.tika.server.core.TikaServerCli"

SERVER_JAR="$(find /usr/local/bin -type f -name "tika-server-*.jar" | sort | tail -1)"
require_file_readable "${SERVER_JAR}"
execute java -cp "${SERVER_JAR}:${CP}" -p "${MP}" "${TIKA_SERVER_CLASS}" "${EXTRA_ARGS[@]}" --port "${PORT}" --host "*" "${TIKA_CONF[@]}"
